### ISSUE TITLE
Unable to run command with out error - no file of directory 

### ISSUE THREAD

**Issue by TimGrist** [abraham-leal/kafka-idle-topics#12]
<img width="1028" alt="MicrosoftTeams-image (2)" src="https://github.com/abraham-leal/kafka-idle-topics/assets/49943799/e7c97693-0b42-4eab-ba63-f91aeb0c3036">

and 

![image-20240109-154050](https://github.com/abraham-leal/kafka-idle-topics/assets/49943799/8aaded79-eb10-4d43-a25a-78ed2e89e134)

This maybe an issue with parameters or the way we are issuing the command please advise

**Comment by aadubey** [comment]
Thanks for raising these issues Tim. very helpful.

The go-build issue (which is image 2) was more of a local go setup issue which was resolved and isn't a problem.

I can see that the docker image does have an exec issue. We'll look at this and confirm back. It

```
 % docker run  -e KAFKA_BOOTSTRAP=“pkc-5roon.us-east-1.aws.confluent.cloud:9092” -e KAFKA_USERNAME=DET6LTDOUKFJNY2I   -e KAFKA_PASSWORD=“cUNnAtdrA8V/UawieW7sRwI/1fShRThZCFVmxg5aDeOCR8Su+O903BiYGNHYU6jd” abrahamleal/kafka-idle-topics:latest  
exec /kafka-idle-topics: no such file or directory
```

**Comment by aadubey** [comment]
Hi Tim - Thank you for raising the issue. Confirming that we are looking into the docker issue.

Also, as discussed in the office hours call, the go-client issue was local to the machine where this was being built and is resolved now.

**Comment by abraham-leal** [comment]
README is updated with the right build pattern. Thanks for reporting this issue!
