### ISSUE TITLE
Should this exclude dlq topics??

### ISSUE THREAD

**Issue by vamsikrishnags** [abraham-leal/kafka-idle-topics#4]
Not really an issue but a Suggestion.
First of all, great tool.. Thanks Abraham.

I ran it for a cluster on CC. It listed dlq topics as well.
dlq topics are connector-created and are required. 
I suggest to either flag this as a message, say at the beginning of text file, to carefully decide which topics to be deleted.
For eg; dlq topics, retry topics(created by devs/ applications), error topics (generally created by HTTP Sink Connector)
All these topics are generally empty but still required.

**Comment by abraham-leal** [comment]
This is a great idea, will incorporate in the next release. Thanks for the feedback!

**Comment by abraham-leal** [comment]
This is solved in the next release.
