### ISSUE TITLE
Support Team Issues

### ISSUE THREAD

**Issue by SandeepSehra** [abraham-leal/kafka-idle-topics#7]
We are currently testing the tool and have issues with running the tool  as it appears to fail if the topic list being queried is greater that 100+ and is dependant on the topics an api key has.  
For a client the tool would work well but for a support team it would mean creating and maintaining  over 10 new service accounts as we have over 1000 topics which is not practical. We also would prefer more details in the output as we can not risk removing client topics with proper safeguards.
Is it possible to update the code

- Resolve the issue with querying large number of topics (may not be possible)

- Restrict queries to a list in a file or  topic prefix rather that the access available to an api-key 

- update the output to include some verification or date last used as well as topic name so we can sort by least active 

- update the docker image to allow the use of the additional parameter (-idleMinutes) that can be used on the command line

**Comment by abraham-leal** [comment]
These are all excellent ideas for improvement. I have carved out time in Q1 for improvements in this project, I’m pretty sure these should be able to be implemented. In the meantime, I am happy to take any PRs related to it. If anyone starts working on it please comment here so there isnt duplicate work in Q1.

**Comment by abraham-leal** [comment]
Thanks for the feedback. The following will be implemented in v1.1:

- Resolve the issue with querying large number of topics (may not be possible)
- Restrict queries to a list in a file or topic prefix rather that the access available to an api-key
- update the docker image to allow the use of the additional parameter (-idleMinutes) that can be used on the command line
      - This should be possible by setting an env variable to the docker run now.

I've decided not to implement the extra metadata of the topic in the output. This information is pretty widely available now in multiple monitoring tools for kafka, so it would be redundant work.
